### ISSUE TITLE
Commit name

### ISSUE THREAD

**Issue by Trinidad-KianLee** [PUP-BSIT/ex16-sixth_sense#7]
Good day, Team.

As you can see in my commits it has the name of "Reyes-PaulAngelo". It's because right now I'm at school borrowing his laptop since my laptop is broken since Friday last week and he let me borrowed his laptop for today. I apologize for the mistakes. I didn't see that his account is still connected in the VsCode and I'm in a rush right now due to accreditation. Thank you for understanding!

**Comment by Escuro-JohnDenielL** [comment]
Got it Kian

**Comment by Gasta-Marc-Oliver** [comment]
Hello Kian, 

Thanks for explaning the situtiation, now I understand why. Make sure to check it next time.

**Comment by IlaganJireh** [comment]
Hello Kian,

It's okay since you're in a rush due to the accreditation tasks you are assigned to. We all make mistakes and thanks for addressing the situation, take care!

**Comment by armedillaalliyah** [comment]
Thanks Kian, that explanation clears things up. Let's double-check similar situations in the future to avoid mistakes.
